### ISSUE TITLE
LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library

### ISSUE THREAD

**Issue by trookie2000** [hamflx/call-net-from-rust-statically#1]
执行cargo build后出错
出现错误的原因： = note:   正在创建库 D:\code\rust\call-net-from-rust-statically\target\debug\deps\call_net_from_rust_statically.lib 和对象 D:\code\rust\call-net-from-rust-statically\target\debug\deps\call_net_from_rust_statically.exp
          LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
          Runtime.WorkstationGC.lib(PalRedhawkMinWin.cpp.obj) : error LNK2019: 无法解析的外部符号 __imp_CoWaitForMultipleHandles，函数 PalCompatibleWaitAny 中引用了该符号
          des-lib.lib(des-lib.obj) : error LNK2001: 无法解析的外部符号 CoInitializeEx
          des-lib.lib(des-lib.obj) : error LNK2001: 无法解析的外部符号 CoUninitialize
          des-lib.lib(des-lib.obj) : error LNK2001: 无法解析的外部符号 CoGetApartmentType
          des-lib.lib(des-lib.obj) : error LNK2001: 无法解析的外部符号 CoCreateGuid
          des-lib.lib(des-lib.obj) : error LNK2001: 无法解析的外部符号 LoadStringW
          D:\code\rust\call-net-from-rust-statically\target\debug\deps\call_net_from_rust_statically.exe : fatal error LNK1120: 6 个无法解析的外部命令。
我查看了sdk里的文件，没有window.lib，build.rs中部分代码（
 1  println!("cargo:rustc-link-lib=static=windows");
 2  println!("cargo:rustc-link-lib=static=bootstrapperdll");
 3  println!("cargo:rustc-link-lib=static=Runtime.WorkstationGC");
 4  println!("cargo:rustc-link-lib=static=System.Globalization.Native.Aot");
 5  println!("cargo:rustc-link-lib=static=des-lib");）
    ，注释掉第一行报错如上，不注释第一行报错信息为：LINK : fatal error LNK1181: 无法打开输入文件“windows.lib”
这是为什么？该怎么解决

**Comment by hamflx** [comment]
windows.lib是windows这个crate提供的，好像后来windows这个crate升级导致这个文件没了，你看看lock文件里的这个版本号，适当降低一下试试，手上暂时没有电脑，不好排查。

**Comment by hamflx** [comment]
第一行不能注释，是必须的。

**Comment by hamflx** [comment]
拉一下最新代码，已经支持最新版本的 windows crate。变更内容：https://github.com/hamflx/call-net-from-rust-statically/commit/c965b864417c174b30c53df58ab7632fbb78c0c6 。

**Comment by trookie2000** [comment]
> 拉一下最新代码，已经支持最新版本的 windows crate。变更内容：[c965b86](https://github.com/hamflx/call-net-from-rust-statically/commit/c965b864417c174b30c53df58ab7632fbb78c0c6) 。

多谢了！输结果应该是这样的？
cipher_text: 00204726f99aaceb36b10b102e36c4c9
plain_text: message

**Comment by hamflx** [comment]
@trookie2000 是的。刚刚又更新了，目前也支持 Linux。

**Comment by trookie2000** [comment]
太棒了！
