### ISSUE TITLE
无法打开输入文件“des-lib.lib”

### ISSUE THREAD

**Issue by amtf-ly** [hamflx/call-net-from-rust-statically#2]
大神您好，我用
cargo run
运行您的项目
控制台提示错误
“
  = note: LINK : fatal error LNK1181: 无法打开输入文件“des-lib.lib”
error: could not compile `call-net-from-rust-statically` (bin "call-net-from-rust-statically") due to 1 previous error
”
您知道是什么原因吗？

**Comment by hamflx** [comment]
文章中如下的命令执行了吗？

```bash
cd des-lib
dotnet publish -r win-x64 -c Release
```
